version: 2

endpoint: htps://app.fossa.io
# api_key: some-key-here

project:
  type: git
  name: github.com/ManaZeak/ManaZeak
  revision: 9ad32d41ed38b5952b40af5c67185ed97c86f31a

modules:
  - path: ./cmd/fossa
    type: nodejs
    options:
      allowUnresolved: false
    project:
      type: custom
      name: github.com/fossas/example-managed-build