sudo: required
dist: xenial
git:
  depth: false
before_install:
  - git fetch --unshallow
  - sudo apt-get update -qq
  - sudo apt-get install -qq pylint
addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=ManaZeak
