sudo: required
dist: xenial
language: java
git:
  depth: false
before_install:
  - git fetch
  - cd back
addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
script:
  - mvn clean verify sonar:sonar -Ptravis -Dsonar.projectKey=ManaZeak
