sudo: required
dist: trusty
language: python
python: 3.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pylint
install: pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
script: sonar-scanner
