sudo: required
dist: trusty
language: python
python: 3.6

install:
  - git fetch --unshallow
  - sudo apt-get update -qq
  - sudo apt-get install -qq pylint nodejs npm
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - pip3 install -r requirements.txt
  - cd ../
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
  - sudo sh -c 'echo export PATH=/home/travis/build/Squadella/sonar-scanner-3.2.0.1227-linux/bin:$PATH >> $HOME/.bashrc'
  - source $HOME/.bashrc
  - cd ./ManaZeak

script: sonar-scanner -D sonar.login=$SONARCLOUDKEY