sudo: required
dist: trusty
language: python
python: 3.6
before_install:
  - git fetch --unshallow
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-pip
  - sudo apt-get upgrade -y
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
  - sudo mv sonar-scanner-3.2.0.1227-linux /opt/sonar/
install:
  - pip3 install -r requirements.txt

addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
script: sonar-scanner