sudo: required
dist: xenial
language: python
python: 3.7.1
before_install:
  - git fetch --unshallow
  - sudo apt-get update -qq
  - sudo apt-get install -qq pylint
before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"
install:
  - pip install -r requirements.txt
  - mv docker-compose.yml.travis docker-compose.yml
  - docker-compose build
  - docker-compose up -d
  - "pylint app -r n --msg-template=\"{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}\" > report.txt"
addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
script:
  - sonar-scanner
