sudo: true
language: python
python: 3.6
before_install: sudo apt install python3-pip
install: pip-3.3 install -r requirements.txt

addons:
  sonarcloud:
    organization: "manazeak"
    token: SONARCLOUDKEY
