dist: xenial
language: java
git:
  depth: false
services:
  - xvfb
before_install:
  - git fetch
  - cp .env.travis .env
  - docker-compose up -d db
  - apt -y install firefox
addons:
  sonarcloud:
    organization: "manazeak"
    token: $SONARCLOUDKEY
  # The url of the database in a container.
  hosts:
    - db
script:
  - mvn clean verify sonar:sonar -Ptravis -Dsonar.projectKey=ManaZeak
