version: '3'
services:
    db:
        image: postgres:latest
        container_name: db
        environment:
            POSTGRES_DB: music
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: rootroot
            volumes:
                - .:/library
            expose:
                - "5432"
            ports:
                - "5432:5432"

    web:
        build: .
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        volumes:
            - /home/pierre/Documents/ACDC/:/library
            - ./static:/static
            - .:/ManaZeak
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: ng01
        ports:
            - "80:8000"
        volumes:
            - /home/pierre/Documents/ACDC/:/library
            - ./nginx/config:/etc/nginx/conf.d
            - ./static:/static
        depends_on:
            - web

    moodbar:
        build: ./moodbar
        container_name: moodbar
        command: bash -c "python moodbarGenerator.py"
        volumes:
            - /home/pierre/Documents/ACDC/:/library
            - /home/pierre/Documents/Gitlab/ManaZeak/static/mood/:/moodbar/static
            - /home/pierre/Documents/Gitlab/ManaZeak/scripts/:/moodbar

    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing01
        volumes:
            - /home/pierre/Documents/ACDC/:/var/syncthing
        ports:
            - "127.0.0.1:8384:8384"
            - "22000:22000"
            - "21027:21027/udp"
