version: '3.4'
services:

    # The database of the backend application.
    db:
        image: postgres:14-alpine
        container_name: manazeak_postgresql
        environment:
            POSTGRES_DB: music
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ${DB_DATA}:/var/lib/postgresql/data
        # Ports used to access the database from the outside (can be removed for prod scenarios).
        ports:
            - "5432:5432"

    # The backend application contains all the hidden logic for the front.
    back:
        build:
            context: .
            target: ${BACK_TARGET}
            dockerfile: back/Dockerfile
        container_name: manazeak_app
        # Debug ports.
        ports:
            - "5005:5005"
            - "8080:8080"
            - "35729:35729"
        volumes:
            - ${RESOURCES_PATH}:/resources
            - ${LIBRARY_PATH}:/library
            - ${LOGS_PATH}:/log
            - ${ASSETS_PATH}:/assets
        links:
            - db
        depends_on:
            - db

    # This container allows serving the static files and the JS.
    # Also is the reverse proxy for the backend application.
    nginx:
        image: nginx:latest
        container_name: manazeak_nginx
        ports:
            - "80:8080"
        volumes:
            - ${LIBRARY_PATH}:/library
            - ${RESOURCES_PATH}:/resources
            - ./docker/nginx/config:/etc/nginx/conf.d
            - ./static:/static
        depends_on:
            - back
        links:
            - back
            - moodbar

    # This container is used to generate the file containing the encoded moodbars.
    moodbar:
        image: manazeak/moodbar_docker
        container_name: manazeak_moodbar
        volumes:
            - ${LIBRARY_PATH}:/library
            # This folder contains the moodbar generated by the container.
            - ${RESOURCES_PATH}:/resources
        links:
            - back
        ports:
            - "4545:4545"

    syncthing:
        image: syncthing/syncthing:latest
        container_name: manazeak_syncthing
        # For local discovery use this :
        # network_mode: "host"
        volumes:
            - ${LIBRARY_PATH}:/ManaZeak
            - ${ASSETS_PATH}:/Pictures # Path leading to the ManaZeak Pictures (artists face, genre and producer logo)
        ports:
            - "127.0.0.1:8384:8384"
            - "22000:22000"
            - "21027:21027/udp"
