# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-26 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('numberOfDisc', models.IntegerField(null=True)),
                ('numberTotalTrack', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('path', models.FilePathField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('isLibrary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('composer', models.CharField(max_length=1000, null=True)),
                ('performer', models.CharField(max_length=1000, null=True)),
                ('number', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('lyrics', models.CharField(max_length=42000, null=True)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('bitRate', models.IntegerField(null=True)),
                ('bitRateMode', models.IntegerField(null=True)),
                ('sampleRate', models.IntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('discNumber', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('lastModified', models.DateField(auto_now=True, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Album')),
                ('artist', models.ManyToManyField(to='app.Artist')),
                ('fileType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FileType')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='app.Artist'),
        ),
    ]
