# Generated by Django 2.1.2 on 2019-02-02 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(max_length=1000, unique=True)),
                ('folderName', models.CharField(max_length=250)),
                ('folderSize', models.IntegerField()),
                ('title', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteCodeEnabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(max_length=1000, unique=True)),
                ('folderName', models.CharField(max_length=1000, null=True, unique=True)),
                ('folderSize', models.IntegerField()),
                ('picture', models.URLField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
                ('realName', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('picture', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=1000)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=33, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryScanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTracks', models.IntegerField()),
                ('processedTrack', models.IntegerField()),
                ('isScanned', models.BooleanField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Library')),
            ],
        ),
        migrations.CreateModel(
            name='MoodAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.FloatField()),
                ('g', models.FloatField()),
                ('b', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Playlist', max_length=100)),
                ('listeningTime', models.IntegerField()),
                ('isLibrary', models.BooleanField()),
                ('isPublic', models.BooleanField()),
                ('description', models.CharField(max_length=5000, null=True)),
                ('picture', models.URLField(max_length=1000, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('picture', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(max_length=1000, unique=True)),
                ('fileName', models.CharField(max_length=250)),
                ('fileSize', models.IntegerField()),
                ('mood', models.URLField(max_length=1000, null=True)),
                ('lastModified', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('lyrics', models.CharField(max_length=42000, null=True)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('trackNumber', models.IntegerField(null=True)),
                ('trackTotal', models.IntegerField()),
                ('discNumber', models.IntegerField(null=True)),
                ('duration', models.FloatField()),
                ('bitRate', models.IntegerField(null=True)),
                ('bitRateMode', models.IntegerField(null=True)),
                ('sampleRate', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('playCounter', models.IntegerField(default=0)),
                ('downloadCounter', models.IntegerField(default=0)),
                ('scanned', models.BooleanField(default=False)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Album')),
                ('albumArtists', models.ManyToManyField(related_name='album_artists', to='app.Artist')),
                ('artists', models.ManyToManyField(to='app.Artist')),
                ('composers', models.ManyToManyField(related_name='composer_artists', to='app.Artist')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cover')),
                ('fileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FileType')),
                ('genres', models.ManyToManyField(to='app.Genre')),
                ('moodAverage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.MoodAverage')),
                ('performers', models.ManyToManyField(related_name='performer_artists', to='app.Artist')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='TrackInScopeAverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDisc', models.IntegerField(null=True)),
                ('totalTrack', models.IntegerField(null=True)),
                ('totalDuration', models.FloatField()),
                ('averageTrackDuration', models.FloatField()),
                ('averageBitRate', models.FloatField(null=True)),
                ('averageSampleRate', models.FloatField(null=True)),
                ('averageBpm', models.FloatField(null=True)),
                ('flacPercentage', models.FloatField()),
                ('averageMood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.MoodAverage')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FilePathField(default='static/default/user.svg')),
                ('language', models.CharField(max_length=5, null=True)),
                ('groups', models.ManyToManyField(to='app.Group')),
                ('inviteCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.InviteCode')),
                ('usedInviteCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_invite_code', to='app.InviteCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeAverages'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeAverages'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.AddField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist'),
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(to='app.Permissions'),
        ),
        migrations.AddField(
            model_name='genre',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeAverages'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='app.Genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeAverages'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='defaultGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
        migrations.AddField(
            model_name='album',
            name='composers',
            field=models.ManyToManyField(related_name='album_composers', to='app.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cover'),
        ),
        migrations.AddField(
            model_name='album',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producer'),
        ),
        migrations.AddField(
            model_name='album',
            name='releaseArtist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_release_artist', to='app.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeAverages'),
        ),
    ]
