# Generated by Django 2.1.2 on 2018-12-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True, unique=True)),
                ('totalDisc', models.IntegerField(null=True)),
                ('totalTrack', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviteCodeEnabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
                ('realName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=1000)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=33, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FilePathField(max_length=1000, unique=True)),
                ('coverLocation', models.URLField(max_length=1000, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('year', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('bpm', models.IntegerField(null=True)),
                ('lyrics', models.CharField(max_length=42000, null=True)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('bitRate', models.IntegerField(null=True)),
                ('bitRateMode', models.IntegerField(null=True)),
                ('sampleRate', models.IntegerField(null=True)),
                ('duration', models.FloatField(null=True)),
                ('discNumber', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('lastModified', models.DateField(auto_now=True, null=True)),
                ('moodbar', models.URLField(max_length=1000, null=True)),
                ('scanned', models.BooleanField(default=False)),
                ('playCounter', models.IntegerField(default=0)),
                ('downloadCounter', models.IntegerField(default=0)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Album')),
                ('artist', models.ManyToManyField(to='app.Artist')),
                ('composer', models.ManyToManyField(related_name='composer_artists', to='app.Artist')),
                ('fileType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FileType')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Genre')),
                ('performer', models.ManyToManyField(related_name='performer_artists', to='app.Artist')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FilePathField(default='/defaultimgpath')),
                ('language', models.CharField(max_length=5, null=True)),
                ('groups', models.ManyToManyField(to='app.Group')),
                ('inviteCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.InviteCode')),
                ('usedInviteCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_invite_code', to='app.InviteCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(to='app.Permissions'),
        ),
        migrations.AddField(
            model_name='applicationconfiguration',
            name='defaultGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='app.Artist'),
        ),
    ]
