# Generated by Django 2.1.2 on 2018-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTracks', models.IntegerField()),
                ('listeningTime', models.IntegerField()),
                ('averageBitRate', models.IntegerField()),
                ('isLibrary', models.BooleanField()),
                ('isPublic', models.BooleanField()),
                ('track', models.ManyToManyField(to='app.Track')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist'),
        ),
    ]
