# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='jsonExport',
            new_name='jsonExportAlbumView',
        ),
        migrations.AddField(
            model_name='playlist',
            name='jsonExportListView',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
