# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackincludedinplaylist',
            name='playList',
        ),
        migrations.RemoveField(
            model_name='trackincludedinplaylist',
            name='track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(to='app.Track'),
        ),
        migrations.DeleteModel(
            name='TrackIncludedInPlaylist',
        ),
    ]
