# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171212_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='listeningPercentage',
            field=models.FloatField(null=True),
        ),
    ]
