# Generated by Django 2.1.2 on 2019-03-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190304_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeStats'),
        ),
    ]
