# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_track_bitratemode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lastModified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
