# Generated by Django 2.1.2 on 2018-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_applicationconfiguration_defaultgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
