# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171214_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='jsonExportAlbumView',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='jsonExportListView',
        ),
    ]
