# Generated by Django 2.1.2 on 2019-03-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190316_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='folderSize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='realName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeStats'),
        ),
    ]
