# Generated by Django 2.1.2 on 2018-12-21 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20181202_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='composer',
            new_name='composers',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='performer',
            new_name='performers',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Playlist', max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
