# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170921_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(null=True, to='app.Artist'),
        ),
    ]
