# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170921_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.FilePathField(max_length=1000),
        ),
    ]
