# Generated by Django 2.1.2 on 2019-01-11 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181221_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryScanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTracks', models.IntegerField()),
                ('processedTrack', models.IntegerField()),
                ('isScanned', models.BooleanField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Library')),
            ],
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='track',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
