# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171216_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncthingKey', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
