# Generated by Django 2.1.2 on 2019-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190316_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.FilePathField(max_length=1000, null=True, unique=True),
        ),
    ]
