# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='isLibrary',
            field=models.BooleanField(default=False),
        ),
    ]
