# Generated by Django 2.1.2 on 2019-03-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190316_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='composers',
        ),
        migrations.AlterField(
            model_name='album',
            name='releaseArtist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album_release_artist', to='app.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackTotal',
            field=models.IntegerField(null=True),
        ),
    ]
