# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_adminoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
    ]
