# Generated by Django 2.1.2 on 2019-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190317_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='folderSize',
            field=models.IntegerField(null=True),
        ),
    ]
