# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_track_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='coverLocation',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
