# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170922_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='numberTotalTrack',
        ),
        migrations.AddField(
            model_name='album',
            name='numberTotalTrack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='NumberOfDisc',
            field=models.IntegerField(null=True),
        ),
    ]
