# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170926_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
        ),
    ]
