# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170922_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='app.Artist'),
        ),
    ]
