# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_track_coverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='jsonInfo',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
