# Generated by Django 2.1.2 on 2019-03-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190317_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Producer'),
        ),
        migrations.AlterField(
            model_name='album',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeStats'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
