# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=33)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('inviteCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.InviteCode')),
            ],
        ),
        migrations.AddField(
            model_name='adminoptions',
            name='inviteCodeEnabled',
            field=models.BooleanField(default=False),
        ),
    ]
