# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170923_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='NumberOfDisc',
            new_name='numberOfDisc',
        ),
    ]
