# Generated by Django 2.1.2 on 2019-03-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190317_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TrackInScopeStats'),
        ),
    ]
