# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_playlist_jsoninfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='jsonInfo',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
