# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userpreferences_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoptions',
            name='bufferPath',
            field=models.FilePathField(max_length=1000, null=True),
        ),
    ]
