# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171003_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='isScanned',
            field=models.BooleanField(default=False),
        ),
    ]
