# Generated by Django 2.1.2 on 2019-03-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190323_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='moodAverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.MoodAverage'),
        ),
    ]
