# Generated by Django 2.1.2 on 2019-04-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190323_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.AlterField(
            model_name='cover',
            name='location',
            field=models.URLField(max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
