# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_library_convertid3'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playCounter',
            field=models.IntegerField(default=0),
        ),
    ]
