# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_shuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='moodbar',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
