# Generated by Django 2.2.2 on 2019-07-27 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumShuffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playlist')),
                ('trackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Track')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
