# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180131_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='refreshView',
            field=models.BooleanField(default=True),
        ),
    ]
