# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_playlist_refreshview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.FloatField(default=0)),
                ('isGain', models.BooleanField(default=False)),
                ('baseMultiplier', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('coinGain', models.IntegerField(default=0)),
                ('coinLoss', models.IntegerField(default=0)),
                ('streakGain', models.IntegerField(default=0)),
                ('streakLoss', models.IntegerField(default=0)),
                ('bubbles', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='income',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='loss',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='streak',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='totalListeningTime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='globalGain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='globalLoss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='miningGain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='miningLoss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transactionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransactionType'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
