# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180217_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
