# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180225_1103'),
        ('app', '0016_playlist_description'),
    ]

    operations = [
    ]
