# Generated by Django 2.2.3 on 2019-12-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191027_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTrackSortedByName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Track')),
            ],
        ),
        migrations.CreateModel(
            name='RandomArtistSortedByName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Artist')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='RandomAlbumSortedByArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Album')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
            ],
        ),
    ]
