# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171104_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
