# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_merge_20180422_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('firstHint', models.CharField(max_length=10000)),
                ('secondHint', models.CharField(max_length=10000)),
                ('thirdHint', models.CharField(max_length=10000)),
                ('reward', models.IntegerField()),
                ('title', models.CharField(max_length=10000)),
                ('isHidden', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
