# Generated by Django 2.2.3 on 2019-12-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_randomalbumsortedbyartist_randomartistsortedbyname_randomtracksortedbyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomGenreSortedByName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Genre')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
            ],
        ),
    ]
