# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='firstHint',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='secondHint',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='thirdHint',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='title',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='picture',
            field=models.FilePathField(default='/defaultimgpath'),
        ),
    ]
