# Generated by Django 2.2.3 on 2019-12-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_randomgenresortedbyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTrackSortedByArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Track')),
            ],
        ),
    ]
