# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_track_crc'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='jsonExport',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
