# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_playlist_jsonexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffleEnabled', models.BooleanField(default=False)),
                ('randomEnabled', models.BooleanField(default=False)),
                ('viewMode', models.IntegerField(max_length=10)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
