# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_playlistsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsettings',
            name='viewMode',
            field=models.IntegerField(),
        ),
    ]
