# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171120_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsettings',
            name='randomEnabled',
        ),
        migrations.RemoveField(
            model_name='playlistsettings',
            name='shuffleEnabled',
        ),
        migrations.AddField(
            model_name='playlistsettings',
            name='randomMode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlistsettings',
            name='repeatEnabled',
            field=models.IntegerField(default=0),
        ),
    ]
