# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171120_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='jsonExport',
            new_name='jsonExportListView',
        ),
        migrations.AddField(
            model_name='playlist',
            name='jsonExportAlbumView',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
