# Generated by Django 2.2.3 on 2019-12-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_randomartistsortedbyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomLabelSortedByName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Label')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
            ],
        ),
    ]
