# Generated by Django 2.2.3 on 2020-02-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_randomlabelsortedbyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCountrySortedByName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashIndex', models.IntegerField(db_index=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Country')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Playlist')),
            ],
        ),
    ]
