# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_history_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.TimeField(),
        ),
    ]
