# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171204_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='downloadCounter',
            field=models.IntegerField(default=0),
        ),
    ]
