# Generated by Django 2.2.4 on 2020-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_suggestion_suggestionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='code',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
