# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_track_downloadcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_test',
                'managed': False,
            },
        ),
    ]
