# Generated by Django 2.2.4 on 2020-04-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200406_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.SuggestionType'),
            preserve_default=False,
        ),
    ]
