# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackView',
            fields=[
                ('track_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('track_location', models.FilePathField(max_length=1000)),
                ('track_title', models.CharField(max_length=1000)),
                ('track_year', models.IntegerField(null=True)),
                ('track_composer', models.CharField(max_length=1000, null=True)),
                ('track_performer', models.CharField(max_length=1000, null=True)),
                ('track_number', models.IntegerField(null=True)),
                ('track_bpm', models.IntegerField(null=True)),
                ('track_lyrics', models.CharField(max_length=42000, null=True)),
                ('track_comment', models.CharField(max_length=10000, null=True)),
                ('track_bitRate', models.IntegerField(null=True)),
                ('track_bitRateMode', models.IntegerField(null=True)),
                ('track_sampleRate', models.IntegerField(null=True)),
                ('track_duration', models.FloatField(null=True)),
                ('track_discNumber', models.IntegerField(null=True)),
                ('track_size', models.IntegerField(null=True)),
                ('track_lastModified', models.DateField(auto_now=True, null=True)),
                ('track_album_id', models.BigIntegerField()),
                ('track_fileType_id', models.BigIntegerField()),
                ('track_mood', models.URLField(max_length=1000, null=True)),
                ('track_download_counter', models.IntegerField(default=0)),
                ('album_title', models.CharField(max_length=1000, null=True)),
                ('genre_id', models.BigIntegerField()),
                ('genre_name', models.CharField(max_length=1000, null=True)),
                ('artist_name', models.CharField(max_length=1000, null=True)),
                ('artist_id', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'app_test',
                'managed': False,
            },
        ),
    ]
