# Generated by Django 2.2.4 on 2020-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200406_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tracksAdded', models.IntegerField(null=True)),
                ('tracksModified', models.IntegerField(null=True)),
            ],
        ),
    ]
