# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_trackview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackview',
            table='app_track_view',
        ),
    ]
