# Generated by Django 2.2.4 on 2020-06-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_libraryscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='location',
            field=models.FilePathField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.FilePathField(db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='cover',
            name='location',
            field=models.URLField(db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(db_index=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='location',
            field=models.FilePathField(db_index=True, max_length=1000, unique=True),
        ),
    ]
