name: ManaZeak continuous integration

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: squadella/maven-firefox-chromium-jdk11
      options: --user 1001
    # Allows to launch a postgresql service for the unit test of the java app
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: music
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setting up test folders
      run: sudo mkdir -p /resources/avatars/
    - name: Build with Maven
      run: mvn clean verify sonar:sonar -Ptravis -Dsonar.projectKey=ManaZeak
