name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: squadella/maven-firefox-chromium-jdk11
      options: --user 1001
    # Allows to launch a postgresql service for the unit test of the java app
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: music
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 11
        distribution: adopt 
    - name: Build with Maven
      run: mvn clean verify sonar:sonar -Ptravis -Dsonar.projectKey=ManaZeak -Dsonar.organization=manazeak -Dsonar.scm.provider=git -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
    - name: Send success message to matrix channel
      uses: fadenb/Matrix-Chat-Message@v0.0.6
      if: success()
      with:
        homeserver: ${{ secrets.MATRIX_SERVER }}
        token: ${{ secrets.ACCES_TOKEN }}
        channel: ${{ secrets.INTERNAL_ROOM_ID }}
        message: Success.
